name: Test
on: push
permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v3

      - run: echo "${{ secrets.TEST }}"
